const oncModel = require("./../Models/onc.moel");
const oncServices = async(email,name,req,res) =>{
const isExits = await oncModel.findOne({email})
if (isExits) {
  return;
}
  if (email) {
const responseUp =   await oncModel.create({
  email:email,
  name:name,
  home: [ { name: "home" },{name:"Start"},{name:"Main"},{name:"Front"} ],
  getstart:[{name:"getstart"},{name:"getstarted"},{name:"get start"},{name:"get started"},{name:"Landing"},{name:"Index"}],
  about: [ { name:  "about"},{name:"ab out"},{name:"Company Overview"},{name:"Our Mission"},{name:"Introduction"} ],
  search:[{name: "search"},{name:"Results"},{name:"Query"},{name:"Output"},{name:"searching"}],
  user:[{name: "profile"},{name:"Account"},{name:"Personal"},{name:"Member"},{name:"User"}],
  notification:[{name :"notification"},{name:"noti"},{name:"Alerts"},{name:"Updates"},{name:"Bell"}],
  contect:[{name: "Contact"},{name:"Reach"},{name:"Help"},{name:"tact"}],
  close:[{name:"close"},{name:"Exit"},{name:"Dismiss"}],
  down:[{name:"down"},{name: "below"},{name:"Arrow"},{name:"Scroll"},{name:"Move"},{name:"Lower"}],
  up:[{name:"up"},{name:"above"},{name:"Jump"},{name:"Elevate"}],
  logout:[{name: "logout"},{name:"Log out"}],
  cut:[{name:"cut"},{name:"cat"},{name:"Extract"},{name:"Clear"}],
  whatName:[{name:"what is my name"}],
  whatEamil:[{name: "what is my email"}],
  yourName:[{name:"what is your name"}],
  find: [{name :"find"},{name:"Identify"},{name:"Scan"},{name:"Detect"},{name:"Locate"}],
  language: [{name: "language"}],
  leftScroll: [{name: "left"}],
  rightScroll:[{name: "right"},{name:"write"}],
  all:[{name: "all games"},{name:"List of Games"}],
  top:[{name :"top games"},{name:"topgames"}],
  description:[{name: "description"},{name:"Detail"},{name:"Definition"},{name:"Exposition"},{name:"Clarification"},{name:"Version"},{name:"summary"}],
  category:[{name: "category"},{name:"Class"},{name:"Classification"},{name:"Genre"},{name:"Variety"}],
  game:[{name: "game"},{name:"Khel"},{name:"gameing"},{name:"games"}],
  add:[{name: "add"},{name:"Include"},{name:"Attach"},{name:"Append"},{name:"Insert"},{name:"Contribute"},{name:"Supplement"}],
  mess:[{name: "message"},{name:"Note"},{name:"Letter"},{name:"Word"},{name:"Report"},{name:"Statement"},{name:"Signal"}],
  battle: [{name:"battle games"},{name:"War games"},{name:"royal games"},{name:"Dispute games"},{name:"Conflict games"}, {name:"battle game"},{name:"War game"},{name:"royal game"},{name:"Dispute game"},{name:"Conflict game"}],
  sports:[{name:"Sports games"},{name:"Sport games"},{name:"Athletics games"},{name:"Sporting games"},{name:"Matches games"},{name:"Tournaments games"},{name:"Sports game"},{name:"Athletics game"},{name:"Sporting game"},{name:"Matches game"},{name:"Tournaments game"},{name:"Physical games"},{name:"Sport game"}],
  educational:[{name:"Educational games"},{name:"Tutorial games"},{name:"Academic games"},{name:"Informative games"},{name:"Learning games"},{name:"Scholastic games"},{name:"Educational game"},{name:"Tutorial game"},{name:"Academic game"},{name:"Informative game"},{name:"Learning game"},{name:"Scholastic game"}],
  bordGame:[{name:"Board Game"},{name:"Parlor game"},{name:"Table game"},{name:"Indoor game"},{name:"Indoor game"},{name:"Board games"},{name:"Parlor games"},{name:"Tabletop games"},{name:"Indoor games"},{name:"Indoor games"}],
  story:[{name:"story games"},{name:"Narrative game"},{name:"Interactive games"},{name:"Visual novel games"},{name:"Feelings games"},{name:"Emotional games"},{name:"Therapy games"},{name:"story game"},{name:"Narrative game"},{name:"Interactive game"},{name:"Visual novel game"},{name:"Feelings game"},{name:"Emotional game"},{name:"Therapy game"}],
  family:[{name:"family games"},{name:"House games"},{name:"Clan games"},{name:"Kin games"},{name:"Tribe games"},{name:"Lineage games"},{name:"Relatives games"},{name:"family game"},{name:"Household game"},{name:"Clan game"},{name:"Kin game"},{name:"Tribe game"},{name:"Lineage game"},{name:"Relatives game"}],
  action:[{name:"action games"},{name:"Act games"},{name:"Activity games"},{name:"action game"},{name:"Act game"},{name:"Activity game"}],
  advancher:[{name:"adventure games"},{name:"journey games"},{name:"quest games"},{name:"exploration games"},{name:"expedition games"},{name:"adventure game"},{name:"journey game"},{name:"quest game"},{name:"exploration game"},{name:"expedition game"}],
  casual:[{name:"Casual games"},{name:"Informal games"},{name:"Relaxed games"},{name:"Carefree games"},{name:"Laid-back games"},{name:"Effortless games"},{name:"Casual game"},{name:"Informal game"},{name:"Relaxed game"},{name:"Carefree game"},{name:"Laid-back game"},{name:"Effortless game"}],
  strategy:[{name:"strategy games"},{name:"Plan games"},{name:"Scheme games"},{name:"Tactic games"},{name:"Technique games"},{name:"strategy game"},{name:"Plan game"},{name:"Scheme game"},{name:"Tactic game"},{name:"Technique game"}],
  indie:[{name:"Indie games"},{name:"Independent games"},{name:"Alternative games"},{name:"Quirky games"},{name:"Indie game"},{name:"Independent game"},{name:"Alternative game"},{name:"Quirky game"}],
  card:[{name:"card games"},{name:"Ticket games"},{name:"Pass games"},{name:"Scorecard games"},{name:"Slip games"},{name:"card game"},{name:"Ticket game"},{name:"Pass game"},{name:"Scorecard game"},{name:"Slip game"}],
  multiplayer:[{name:" Multiplayer games"},{name:"Online games"},{name:"Team games"},{name:" Multiplayer game"},{name:"Online game"},{name:"Team game"}],
  arcade:[{name:"arcade games"},{name:"Gallery games"},{name:"Marketplace games"},{name:"Shops games"},{name:"Hallway games"},{name:"Marketplace games"},{name:"arcade game"},{name:"Gallery game"},{name:"Marketplace game"},{name:"Shops game"},{name:"Hallway game"},{name:"Marketplace game"}],
  simulation:[{name:"simulation games"},{name:"Imitation games"},{name:"Copying games"},{name:"Acting games"},{name:"simulation game"},{name:"Imitation game"},{name:"Copying game"},{name:"Acting game"}],
  platformer:[{name:"platformer games"},{name:"Platform games"},{name:"platformer game"},{name:"Platform game"}],
  fighting:[{name:"fighting games"},{name:"Combat games"},{name:"fight games"},{name:"Clash games"},{name:"fighting game"},{name:"Combat game"},{name:"fight game"},{name:"Clash game"}],
  rpg:[{name:"rpg games"},{name:"Role play games"},{name:"Fantasy games"},{name:"Roleplaying games"},{name:"rpg game"},{name:"Role play game"},{name:"Fantasy game"},{name:"Roleplaying game"}],
  racing:[{name:"racing games"},{name:"Vehicle combat games"},{name:"Time trial games"},{name:"Competitive games"},{name:"racing game"},{name:"Vehicle combat game"},{name:"Time trial game"},{name:"Competitive game"}],
  shooter:[{name:"shooter games"},{name:"Sniper games"},{name:"weapon games"},{name:"shooter game"},{name:"Sniper game"},{name:"weapon game"}],
  puzzle:[{name:"puzzle games"},{name:"Hidden object games"},{name:"logic games"},{name:"puzzle game"},{name:"Hidden object game"},{name:"logic game"}],
  tag:[{name:"tag"},{name:"tags"}],
  platfrom:[{name:"devices"},{name:"Gadget"},{name:"device"},{name:"Equipment"},{name:"Hardware"},{name:"Console"}],
  creators:[{name:"creators"},{name:"developers"},{name:"Makers"},{name:"Innovators"}],
  AmyHennig:[{name:"Amy Hennig"},{name:"Amy"},{name:"Hennig"},{name:"AmyHennig"}],
  ShigeruMiyamoto:[{name:"Shigeru Miyamoto"},{name:"ShigeruMiyamoto"},{name:"Shigeru"},{name:"Miyamoto"}],
  CliffBleszinski:[{name:"Cliff Bleszinski"},{name:"CliffBleszinski"},{name:"Cliff"},{name:"Bleszinski"}],
  DavidCage:[{name:"David Cage"},{name:"DavidCage"},{name:"David"},{name:"Cage"}],
  GabeNewell:[{name:"Gabe Newell"},{name:"GabeNewell"},{name:"Gabe"},{name:"Newell"},{name:"Gabby"}],
  TimSchafer:[{name:"Tim Schafer"},{name:"TimSchafer"},{name:"Tim"},{name:"Schafer"}],
  RichardGarriott:[{name:"Richard Garriott"},{name:"RichardGarriott"},{name:"Richard"},{name:"Garriott"}],
  JonathanBlow:[{name:"Jonathan Blow"},{name:"JonathanBlow"},{name:"Jonathan"},{name:"Blow"}],
  BrianFargo:[{name:"Brian Fargo"},{name:"BrianFargo"},{name:"Fargo"},{name:"Brian"}],
  MarkusNotchPersson:[{name:"Markus Notch Persson"},{name:"MarkusNotchPersson"},{name:"Notch"},{name:"Persson"},{name:"Markus"},{name:"Marcus"}],
  RalphHBaer:[{name:"Ralph H. Baer"},{name:"RalphBaer"},{name:"Baer"},{name:"Ralph"}],
  JohnCarmack:[{name:"John Carmack"},{name:"JohnCarmack"},{name:"John"},{name:"Carmack"}],
  ToddHoward:[{name:"Todd Howard"},{name:"ToddHoward"},{name:"Todd"},{name:"Howard"}],
  ForzaHorizon5:[{name:"Forza Horizon 5"},{name:"Forza"}],
  JasonJones:[{name:"Jason Jones"},{name:"JasonJones"},{name:"Jason"},{name:"Jones"}],
  YokoTaro:[{name:"Yoko Taro"},{name:"YokoTaro"},{name:"Taro"},{name:"Yoko"}],
  KenLevine:[{name:"Ken Levine"},{name:"KenLevine"},{name:"Ken"},{name:"Levine"}],
  SidMeier:[{name:"Sid Meier"},{name:"SidMeier"},{name:"Sid"},{name:"Meier"},{name:"sid"}],
  WillWright:[{name:"Will Wright"},{name:"WillWright"},{name:"Will right"}],
  SwenVincke:[{name:"wen Vincke"},{name:"wenVincke"},{name:"wen"},{name:"Vincke"}],
  HideoKojima:[{name:"Hideo Kojima"},{name:"HideoKojima"},{name:"Hideo"},{name:"Kojima"}],
  DynamicMenu:[{name:"Dynamic Menu"},{name:"DynamicMenu"},{name:"Dynamic"}],
  menutop:[{name:"menu top"},{name:"menutop"}],
  settting:[{name:"setting"},{name:"Backdrop"}],
  BalancedMode:[{name:"Balanced Mode"},{name:"Balanced Mod"},{name:"Balanced"}],
  InternetSafetyMode:[{name:"Internet Safety Mode"},{name:"InternetSafetyMode"},{name:"Internet Safety"},{name:"Safety Mode"}],
settingetstarted:[{name:"setting getstarted"},{name:"lobby"},{name:"Started"},{name:"Start"}],
  edit:[{name:"edit"},{name:"profile update"},{name:"Modify"}],
  login:[{name:"login"}],
  sign:[{name:"sign"},{name:"signup"},{name:"sign up"}],
  lastname:[{name : "last name"}],
  emailSLE:[{name: "email"}],
  password:[{name: "password"}],
  gender:[{name: "gender"}],
  name1:[{name: "name"}],
  submit:[{name: "submit"}],
  remove:[{name: "remove"},{name:"Kick out"}],
  tap:[{name:"tap"},{name:"click"},{name:"Hit"},{name:"Press"},{name:"Touch"},{name:"tab"}],
  open:[{name:"open"}],
  blackmithwokong:[{name:"black mith wokong"},{name:"black mith"},{name:"Black"}],
  rdr2:[{name:"rdr2"},{name:"red dead redemption"},{name:"red dead"},{name:"red death"}],
  spiderman:[{name:"spider man"},{name:"spiderman"}],
  valorant:[{name:"valorant"},{name:"valo"},{name:"value"},{name:"valuing"},{name:"relevant"}],
  marvalrivales:[{name:"marval rivales"},{name:"Marvel rivals"}],
  wwe:[{name:"wwe 2k24"},{name:"wwe"},{name:"2k24"}],
  godofwar:[{name:"god of war"},{name:"god"}],
  infinity:[{name:"infinity nikki"},{name:"infinity"}],
  details:[{name:"details"},{name:"Data"},{name:"Features"},{name:"Attributes"},{name:"detail"},{name:"Feature"},{name:"Attribute"}],
  fornight:[{name:"fortnite"},{name:"fornight"},{name:"fortnight"}],
  XKO:[{name:"2XKO"},{name:"2x"},{name:" 2x KO"}],
  ApexLegends:[{name:"Apex Legends"},{name:"Apex Legend"},{name:"Apex"},{name:"Legends"}],
  Warframe:[{name:"Warframe"},{name:"frame"}],
  Tales:[{name:"Tales"},{name:"Tale"},{name:"Tal"},{name:"tails"}],
  DeadorAlive:[{name:"Dead or Alive"},{name:"Dead"},{name:"Alive"},{name:"Dead Alive"}],
  GranblueFant:[{name:"Granblue Fant"},{name:"Granblue"},{name:"Fant"},{name:"Grand blue"}],
  GTA:[{name:"Grand Theft Auto VI"},{name:"gta"},{name:"gta6"},{name:"gta 6"},{name:"Grand Theft Auto 6"}],
  inZOI:[{name:"inZOI"},{name:"zoi"},{name:"Enjoy"}],
  Fable:[{name:"Fable"},{name:"Fab"}],
  Marvel:[{name:"Marvel 1943: Rise of Hydra"},{name:"Marvel 1943"},{name:"Rise of Hydra"}],
  Star:[{name:"Star Wars: Zero Company"},{name:"Star Wars"},{name:"Zero Company"}],
  Warhammer:[{name:"Warhammer 40,000: Boltgun 2"},{name:"Warhammer 40,000"},{name:"Boltgun 2"},{name:"Warhammer"}],
  Onimusha:[{name:"Onimusha: Way of the Sword"},{name:"Onimusha"},{name:"Way of the Sword"}],
  Saros:[{name:"Saros"},{name:"Saro"}],
  Witcher:[{name:"The Witcher 4"},{name:"Witcher"}],
  Project:[{name:"Project Witches"},{name:"Project"},{name:"Witches"}],
  cancal:[{name:"cancal"},{name:"Drop"},{name:"Exit"},{name:"stop"},{name:"Eliminate"}],
  ride5:[{name:"ride 5"},{name:"ride"}],
  palworld:[{name:"palworld"},{name:"pal world"}],
  indianajones:[{name:"indiana jones"},{name:"indianajones"},{name:"indiana jones"}],
  Cyberpunk:[{name:"Cyberpunk"},{name:"Cyber punk"}],
  LegendZelda:[{name:"LegendZelda"},{name:"LegendZelda"},{name:"Zelda"}],
  games:[{name:"games"},{name:"Activity"},{name:"game"}],
  GrandTheftAutoOnline:[{name:"Grand Theft Auto Online"},{name:"Grand Theft Auto"},{name:"Auto Online"}],
  TheLostLegacy:[{name:"Uncharted The Lost Legacy"},{name:"Uncharted The "}],
  Uncharted4:[{name:"Uncharted 4"},{name:"Uncharted"}],
  GTASanAndreas:[{name:"GTA San Andreas"},{name:"GTA San"},{name:"GTASan"}],
  RealmsRuin:[{name:"Realms of Ruin"},{name:"Realms of"}],
  XX30:[{name:"30XX"},{name:"thirty"},{name:"30"}],
  AvatarPandora:[{name:"Avatar: Frontiers of Pandora"},{name:"Avatar"}],
  TheFirstDescendant:[{name:"The First Descendant"},{name:"The First"}],
  ArmoredCoreVI:[{name:"Armored Core VI"},{name:"Armored"}],
  Mirage:[{name:"Assassin's Creed Mirage"},{name:"Assassin's Creed Mirage"},{name:"Mirage"}],
  MetalGearSolidV:[{name:"Metal Gear Solid V: The Phantom Pain"},{name:"Metal Gear Solid"},{name:"The Phantom Pain"},{name:"Metal Gear"}],  
  DoomEternal:[{name:"Doom Eternal"},{name:"DoomEternal"},{name:"Doom"},{name:"Eternal"}],
  ThankGoodness:[{name:"Thank Goodness You’re Here!"},{name:"Thank Goodness You"}],
  TacticalBreachWizards:[{name:"Clair Obscur: Expedition 33:"},{name:"Clair Obscur"}],
  Lorelei:[{name:"Lorelei and the Laser Eyes"},{name:"Lorelei"}],
  CastlevaniaDominus:[{name:"Castlevania Dominus Collection"},{name:"Castlevania"}],
  LikeaDragon:[{name:"Like a Dragon: Infinite Wealth"},{name:"Like a Dragon"}],
  Tsukihime:[{name:"Asphalt 9 "},{name:"Asphalt"}],
  freefire:[{name:"free fire"}],
  Tekken8:[{name:"Tekken 8"},{name:"Tekken"}],
  LastUsPartII:[{name:"The Last of Us Part II Remastered"},{name:"The Last of Us 2"},{name:"The Last of Us two"}],
  Balatro:[{name:"Portal 2"},{name:"Portal"}],
  Dauntless:[{name:"Dauntless"},{name:"Daunt less"}],
  Satisfactory:[{name:"Satisfactory"},{name:"Satis factory"}],
  AnimalWell:[{name:"Animal Well"},{name:"AnimalWell"}],
  UFO50:[{name:"UFO 50"},{name:"50"},{name:"fifty"},{name:"UFO"},{name:"UFO50"}],
  SlaythePrinces:[{name:"Slay the Princess – The Pristine Cut"},{name:"Slay the Princess"}],
  FinalFantasy:[{name:"Final Fantasy VII Rebirth"},{name:"Final Fantasy"},{name:"FinalFantasy"},{name:"Final Fantastic"}],
  MetaphorReFantazio:[{name:"Metaphor: ReFantazio"},{name:"MetaphorReFantazio"},{name:"Metaphor"},{name:"ReFantazio"}],
  BladeSoul:[{name:"Blade & Soul"},{name:"Blade"},{name:"Blade and Soul"},{name:"Blade&Soul"}],
  StarWars:[{name:"Star Wars: The Old Republic"},{name:"Star Wars"},{name:"StarWars"}],
  WarThunder:[{name:"War Thunder"},{name:"WarThunder"},{name:"Thunder"}],
  WorldofTanks:[{name:"World of Tanks"},{name:"WorldTanks"},{name:"Tanks"}],
  Smite:[{name:"Smite"}],
  Paladins:[{name:"Paladins"},{name:"Palad"}],
  Hearthstone:[{name:"Hearth stone"},{name:"Hearthstone"},{name:"Hearth"}],
  TeamFortress2:[{name:"Team Fortress 2"},{name:"Team Fortress"},{name:"TeamFortress"},{name:"Fortress"}],
  Destiny2:[{name:"Destiny 2"},{name:"Destiny"}],
  CallWarzone:[{name:"Call of Duty: Warzone"},{name:"CallofDuty"},{name:"COD"},{name:"Warzone"},{name:"War zone"}],
  GenshinImpact:[{name:"Little Nightmares 3"},{name:"Nightmares 3"},{name:"Little"}],
  TheLastOfUs:[{name:"The Last Of Us"},{name:"TheLastOfUs"}],
  BaldurGate3:[{name:"Baldur's Gate 3"},{name:"BaldurGate"},{name:"Gate 3"},{name:"Gate"}],
  Diablo4:[{name:"Diablo 4"},{name:"Diablo four"}],
  ItTakesTwo:[{name:"It Takes Two"},{name:"ItTakesTwo"},{name:"It Takes 2"},{name:"It Takes"}],
  Civilization7:[{name:"Civilization 7"},{name:"Civilization sevan"},{name:"Civilization"}],
  MetroidPrime:[{name:"Metroid Prime 4"},{name:"Metroid Prime four"},{name:"MetroidPrime"},{name:"Metroid"}],
  SenuaSaga:[{name:"Senua’s Saga: Hellblade II"},{name:"Senua Saga"},{name:"Senua’s Saga"},{name:"Saga"}],
  Avowed:[{name:"Avowed"}],
  KingdomDeliverance2:[{name:"Kingdom Come: Deliverance 2"},{name:"Kingdom"}],
  Fable:[{name:"Fable"}],
  MarvelsWolverine:[{name:"Marvels Wolverine"},{name:"MarvelsWolverine"},{name:"Wolverine"}],
  StarWars:[{name:"Battlefield 6"},{name:"Battle"}],
  TheElder:[{name:"The Elder Scrolls VI"},{name:"The Elder Scrolls four"},{name:"TheElderScrolls"},{name:"The Elder"}],
  TomClancy:[{name:"Tom Clancy's Rainbow Six: Siege"},{name:"Tom Clancy"},{name:"Rainbow"}],
  DiabloIV:[{name:"Diablo IV"},{name:"Diablo four"},{name:"Diablo"}],
  Overwatch2:[{name:"Overwatch 2"},{name:"Overwatch two"},{name:"Overwatch"}],
  Rust:[{name:"Rust"},{name:"Trust"}],
  RocketLeague:[{name:"Rocket League"},{name:"RocketLeague"},{name:"Rocket"}],
  PathofExile2:[{name:"Path of Exile 2"},{name:"Path of Exile two"},{name:"PathofExile"},{name:"Path of Exile"},{name:"Path Exile"}],
  DeltaForce:[{name:"Delta Force"},{name:"DeltaForce"},{name:"Delta"}],
  GrandTheftAutoV:[{name:"Grand Theft Auto V"},{name:"Grand Theft Auto five"},{name:"Grand Theft Auto 5"}],
  HELLDIVERS2:[{name:"HELLDIVERS 2"},{name:"HELLDIVERS two"},{name:"HELLDIVERS"}],
  PUBGBATTLEGROUNDS:[{name:"PUBG BATTLEGROUNDS"},{name:"PUBG"}],
  CallofDuty:[{name:"Call of Duty: Modern Warfare"},{name:"Modern Warfare"},{name:"Modern"}],
  Dota2:[{name:"Dota 2"},{name:"Dota two"}],
  TheSims4:[{name:"The Sims 4"},{name:"The Sims four"},{name:"The Sims"}],
  ROBLOX:[{name:"ROBLOX"}],
 Minecraft:[{name:"Minecraft"}],
  CounterStrike:[{name:"Counter-Strike 2 & GO"},{name:"Counter Strike"},{name:"Strike"}],
 Magic:[{name:"Magic: The Gathering Arena"},{name:"Magic"},{name:"The Gathering Arena"}],
 Chivalry2:[{name:"Chivalry 2"},{name:"Chivalry"}],
  LeagueofLegends:[{name:"League of Legends"},{name:"LeagueofLegends"},{name:"League Legends"},{name:"of Legends"},{name:"LOL"}],
  SidMeier:[{name:"Sid Meiers"},{name:"SidMeiers"},{name:"Meiers"}],
  MovingOut:[{name:"Moving Out"},{name:"MovingOut"},{name:"Moving"}],
  BloonsTD:[{name:"Bloons TD 6"},{name:"Bloons TD six"},{name:"Bloons"}],
  Satisfactory:[{name:"Satisfactory"},{name:"Satis factory"}],
  AmongUs:[{name:"Among Us"},{name:"Among"}],
  EASPORTSFC:[{name:"F1 25"},{name:"f125"}],
  fc25:[{name:"fc25"},{name:"FC 25"}],
  NARAKABLADEPOINT:[{name:"NARAKA BLADEPOINT"},{name:"NARAKA"},{name:"BLADEPOINT"}],
  FarmingSimulator:[{name:"Farming Simulator"},{name:"FarmingSimulator"},{name:"Simulator"},{name:"Farming"}],
  WitchIt:[{name:"gost of yotel"},{name:"yotel"},{name:"gost of"}],
  DeathStranding:[{name:"Death Stranding"},{name:"DeathStranding"},{name:"Stranding"}],
  FarCry5:[{name:"FarCry 5"},{name:"FarCry five"},{name:"FarCry"}],
  ShadowColossus:[{name:"Lego Voyagers"},{name:"Lego"},{name:"Voyagers"}],
  Journey:[{name:"Journey"},{name:"Journey?"}],
  AdventuresofPip:[{name:"Adventures of Pip"},{name:"AdventuresofPip"},{name:"Adventures"}],
  AWayOut:[{name:"A Way Out"},{name:"AWayOut"},{name:"A Way"}],
  Horizon:[{name:"Horizon Zero Dawn"},{name:"Horizon"}],
  TheLegendZelda:[{name:"The Legend of Zelda"},{name:"TheLegendofZelda"},{name:"The Legend Zelda"},{name:"Zelda"}],
  Firewatch:[{name:"Firewatch"},{name:"Fire watch"}],
  LifeStrange:[{name:"Life is Strange"},{name:"Life Strange"},{name:"Strange"}],
  TombRaider:[{name:"Tomb Raider"},{name:"TombRaider"},{name:"Raider"}],
  ClashOfClans:[{name:"Clash Of Clans"},{name:"ClashOfClans"},{name:"COC"}],
  TheOuterWorlds:[{name:"The Outer Worlds 2"},{name:"The Outer Worlds two"},{name:"TheOuterWorlds"},{name:"The Worlds"}],
  Skate4:[{name:"Skate 4"},{name:"Skate four"},{name:"Skate"}],
  SplitFiction:[{name:"Split Fiction"},{name:"Split"},{name:"Fiction"}],
  Kingmakers:[{name:"Kingmakers"},{name:"King makers"},{name:"makers"}],
  TheAlters:[{name:"The Alters"},{name:"TheAlters"},{name:"TheAlters"}],
  Borderlands4:[{name:"Borderlands 4"},{name:"Borderlands four"},{name:"Border lands"}],
  MetalGear:[{name:"Metal Gear Solid Delta: Snake Eater"},{name:"MetalGearSolidDelta"},{name:"Solid Delta"}],
  TwoPointMuseum:[{name:"Two Point Museum"},{name:"TwoPointMuseum"},{name:"Two Point"},{name:"2 point"}],
  MonsterHunter:[{name:"Monster Hunter Wilds"},{name:"MonsterHunterWilds"},{name:"Monster Hunter"},{name:"Monster"}],
  Atofall:[{name:"Atofall"},{name:"Ato fall"},{name:"Autofall"},{name:"Auto fall"}],
  KillingFloor:[{name:"Killing Floor 3"},{name:"Killing Floor three"},{name:"Killing"}],
  TalestheShire:[{name:"Tales of the Shire"},{name:"TalesoftheShire"},{name:"the Shire"},{name:"Tales of the"}],
  SavagePlanet:[{name:"Revenge of the Savage Planet"},{name:"Revenge of the Savage"},{name:"Revenge of the"}],
  PrincePersia:[{name:"PrincePersia"},{name:"Prince"}],
  FragPunk:[{name:"FragPunk"},{name:"Frag Punk"}],
  Assassin:[{name:"Assassin's Creed Shadows"},{name:"Shadows"}],
  OrcsMustDie:[{name:"Orcs Must Die! Deathtrap"},{name:"Deathtrap"}],
  CarXDrift:[{name:"CarX Drift Racing Online"},{name:"Racing Online"},{name:"CarX Drift"},{name:"Car X Drift"}],
  EmpiretheAnts:[{name:"Empire of the Ants"},{name:"the Ants"},{name:"Empire of the"}],
  StarWarsOutlaws:[{name:"Star Wars Outlaws"},{name:"Outlaws"},{name:"Star Wars"}],
  EASPORTS:[{name:"EA SPORTS™ Madden NFL 25"},{name:"EA SPORTS"},{name:"SPORTS"}],
  DuneAwakening:[{name:"Dune: Awakening"},{name:"Dune"}],
  Beaconfire:[{name:"Beacon-fire: Project Salvation Belles"},{name:"Beacon fire"},{name:"Beacon"}],
  Wanderstop:[{name:"Wanderstop"},{name:"Wander stop"},{name:"Under stop"},{name:"Wonder stop"}],
  SlayPrincess:[{name:"Slay the Princess – The Pristine Cut"},{name:"Slay Princess"},{name:"Slay Princess"},{name:"Princess"}],
  MetaphorReFantazio:[{name:"Metaphor: ReFantazio"},{name:"MetaphorReFantazio"},{name:"Metaphor"}],
 EldenRing:[{name:"Elden Ring: Shadow of the Erdtree"},{name:"Elden Ring"},{name:"Alden ring"},{name:"Table ring"}],
 AstroBot:[{name:"Astro Bot"},{name:"AstroBot"},{name:"Bot"},{name:"Astronaut"}],
 DragonsDogma2:[{name:"Dragon's Dogma 2"},{name:"Dragon Dogma two"},{name:"Dragon Dogma"},{name:"Dragon"}],
 KillKnight:[{name:"Kill Knight"},{name:"KillKnight"},{name:"Knight"},{name:"Kill"}],
 TacticalBreachWizards:[{name:"Tactical Breach Wizards"},{name:"TacticalBreach"},{name:"Tactical Wizards"}],
 EternalStrands:[{name:"Eternal Strands"},{name:"EternalStrands"},{name:"Eternal"},{name:"internal"}],
 TankHead:[{name:"Tank Head"},{name:"TankHead"},{name:"Tank"}],
 TheMidnightWalk:[{name:"The Midnight Walk"},{name:"The Midnight"}],
 ZenlessZoneZero:[{name:"Hell Is Us"},{name:"Hell"},{name:"Is Us"}],
 left1:[{name:"left one"},{name:"left 1"}],
 right1:[{name:"right one"},{name:"right 1"}],
  left2:[{name:"left two"},{name:"left 2"},{name:"left to"}],
 right2:[{name:"right two"},{name:"right 2"},{name:"right to"}],
  left3:[{name:"left three"},{name:"left 3"}],
 right3:[{name:"right three"},{name:"right 3"}],
  left4:[{name:"left four"},{name:"left 4"}],
 right4:[{name:"right four"},{name:"right 4"}],
  left5:[{name:"left five"},{name:"left 5"}],
 right5:[{name:"right five"},{name:"right 5"}],
  left6:[{name:"left six"},{name:"left 6"}],
 right6:[{name:"right six"},{name:"right 6"}],
  left7:[{name:"left seveen"},{name:"left 7"}],
 right7:[{name:"right seveen"},{name:"right 7"}],
  left8:[{name:"left eighth"},{name:"left 8"}],
 right8:[{name:"right eighth"},{name:"right 8"}],
 day:[{name:"day"},{name:"days"},{name:"Daily"}],
 week:[{name:"week"},{name:"weeks"}],
 month:[{name:"month"},{name:"months"}],
 year:[{name:"year"},{name:"years"}],
 send:[{name:"send"},{name:"Deliver"},{name:"Shoot"},{name:"Dispatch"}],
playblack:[{name:"play black"},{name:"play Black myth Wokong"},{name:"play wokong"}] ,
playtakken:[{name:"play takken"},{name:"play takken 8"},{name:"play takken eight"}],
trynow:[{name:"trynow"},{name:"try now"}],
chat:[{name:"chat"},{name:"Dialogue"},{name:"Chatter"}],
world:[{name:"world chat"},{name:"universal chat"}],
one:[{name:"one"},{name:"1"}], 
two:[{name:"two"},{name:"2"}],
three:[{name:"three"},{name:"3"}], 
four:[{name:"four"},{name:"4"}], 
five:[{name:"five"},{name:"5"}], 
six:[{name:"six"},{name:"6"}], 
seven:[{name:"seven"},{name:"7"}], 
eight:[{name:"eight"},{name:"8"}], 
nine:[{name:"nine"},{name:"9"}], 
ten:[{name:"ten"},{name:"10"}],  
SystemRequirements:[{name:"System Requirements"},{name:"SystemRequirements"},{name:"Hardware requirements"},{name:"Software requirements"},{name:"Technical requirements"}],
Additionalinformation:[{name:"Additional"},{name:"Supplementary"},{name:"Auxiliary"}],
skip:[{name:"skip"}],
ok:[{name:"ok"}]
  })
}  
}

module.exports = oncServices