const{Schema,model} = require('mongoose');

const Champition = new Schema({
      isRemoved: Boolean,
    name:{
        type:String
    },
   img:{
    type:String
   },
   year:[
    {
        img:{
            type:String
        },
        name:{
            type:String
        },
        video:{
            type:String
        },
        h1:{
            type:String
        },
        h2:{
            type:String
        },
        h3:{
            type:String
        },
        p:{
            type:String
        }
    }
   ],
   top:[
    {
        place:{
            type:String
        },
        img:{
            type:String
        },
        point:{
            type:String
        },
        MVP:{
            type:String
        },
        para:{
            type:String
        }
    }
   ],
   extra:[
    {
        img:{
            type:String
        }
    }
   ],
   year2:[
    {
        img:{
            type:String
        }
    }
   ],
   top2:[
    {
         img:{
            type:String
        }
    }
   ],
   extra2:[
    {
         img:{
            type:String
        }
    }
   ],
   year3:[
    {
         img:{
            type:String
        }
    }
   ],
   top3:[
    {
         img:{
            type:String
        }
    }
   ],
   extra3:[
    {
         img:{
            type:String
        }
    }
   ]
},{suppressReservedKeysWarning: true })

const ChampitionSchema = new model('chamption',Champition);
module.exports = ChampitionSchema;